apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ecommerce-order-service
spec:
  host: order-service-dev.apps.dev.example.com
  path: /api/orders
  to:
    kind: Service
    name: ecommerce-order-service
  port:
    targetPort: 8081
  tls:
    termination: edge
