apiVersion: v1
kind: ConfigMap
metadata:
  name: core-banking-api-config
data:
  SPRING_PROFILES_ACTIVE: "uat"
  DATABASE_URL: "jdbc:postgresql://db-uat.example.com:5432/corebanking_uat"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-uat.example.com:9092"
  LOG_LEVEL: "INFO"
